---
- name: Start apache service
  service:
    name: "{{ apache_service }}"
    state: "started"
    enabled: true
  when:  ansible_os_family == os_family   

- name: Restart apache
  service:
    name: "{{ apache_service }}"
    state: restarted
