---
- name: configer appache with firewall depended on gathering facts
  hosts: all
  become_user: ubuntu
  become: yes
  gather_facts: yes
  roles:
      - facts
      - cacheapt
      - apache
      - firewall