version: '3.8'

services:
  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    volumes:
      - data1:/home/bat/data
    tty: true

  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    volumes:
      - data2:/home/bat/data
    tty: true
volumes:
  data1:
  data2: